"""
schema/columns.py — THE single source of truth for every column in this project.

Project: Evaluating Blockchain-Resolution and Victim-Relay Indicators for
         IoT Botnet Detection

Scope:   DEFENSIVE measurement only. No attack capability, no network activity,
         no contact with real infrastructure. See docs/ethics-and-containment.md.

WHY THIS FILE EXISTS
--------------------
The prototype (`prototype/`) emitted 16 features and one binary label, and
nothing else. That made three things impossible:

  * grouped splits      — no device identifier to group by
  * temporal splits      — no timestamp to order by
  * provenance auditing  — no record of where a row came from

Worse, it made a fourth thing *invisible*: if real-capture rows and locally
generated mock rows were ever concatenated, no column would reveal it, and a
model could learn "which capture is this?" instead of "is this malicious?" and
report a high F1 that measures nothing.

Every column below exists to make one of those four failures either possible
to do correctly, or impossible to do accidentally.

THE TWO-TRACK RULE (non-negotiable, enforced in schema/validate.py)
-------------------------------------------------------------------
Real and mock observations describe DISJOINT label spaces:

    Track A (real, IoT-23)   benign_real, traditional_c2,
                             traditional_botnet_activity
    Track B (mock, local)    benign_mock, blockchain_resolution_mock,
                             victim_relay_mock, combined_mock

No row may carry a research_class from the other track's list. No experiment
may train a single model over the union. The only permitted crossing is
one-directional and reported as a false-positive rate, never as accuracy:
score a Track-B-trained detector against Track-A benign rows.

The reason is not fastidiousness. Real IoT-23 captures physically cannot
contain blockchain-resolution or victim-relay behaviour — that behaviour is
newer than the captures. A model trained on the union would separate the
classes using capture artefacts (TTL, MTU, clock resolution, byte-count
granularity) and the resulting score would be indistinguishable from success.
"""
from __future__ import annotations

# ============================================================================
# SECTION 1 — PROVENANCE / METADATA COLUMNS
# ============================================================================

OBSERVATION_ID = "observation_id"      # str, unique per row
DEVICE_ID = "device_id"                # str, GROUPING key for grouped splits
WINDOW_START = "window_start"          # datetime64[ns], ORDERING key (temporal)
WINDOW_SECONDS = "window_seconds"      # int, always WINDOW_SECONDS_VALUE

# The observation window is fixed project-wide. It is a schema constant rather
# than a tunable because changing it changes the MEANING of every feature
# (scan_rate, login_burst_count and flow_fanout are all per-window counts), so
# results computed at different window sizes are not comparable and must not be
# mixed in one frame. The validator rejects any other value.
WINDOW_SECONDS_VALUE = 300
SOURCE_DATASET = "source_dataset"      # str, enum — see SOURCE_DATASETS
SCENARIO_ID = "scenario_id"            # str, capture/scenario this row is from
CAPTURE_PROVENANCE = "capture_provenance"   # str, enum — real vs synthetic
RESEARCH_CLASS = "research_class"      # str, enum — the 7-class taxonomy
ORIGINAL_LABEL = "original_label"      # str, VERBATIM label from the source
LABEL_BINARY = "label_binary"          # int, 0/1 derived view for binary work

# Sentinel for the binary view of an `unmapped` row. Deliberately NOT 0: an
# unmapped row is one whose source label this project refuses to guess at, and
# defaulting it to "benign" would quietly move unknown traffic into the negative
# class and deflate the measured false-positive rate.
LABEL_BINARY_UNMAPPED = -1

LABEL_CONFIDENCE = "label_confidence"  # str, enum — how the label was obtained
QUALITY_FLAGS = "quality_flags"        # str, ";"-joined flags, "" when clean
N_FEATURES_MISSING = "n_features_missing"   # int, count of NaN feature cells

META_COLS: list[str] = [
    OBSERVATION_ID,
    DEVICE_ID,
    WINDOW_START,
    WINDOW_SECONDS,
    SOURCE_DATASET,
    SCENARIO_ID,
    CAPTURE_PROVENANCE,
    RESEARCH_CLASS,
    ORIGINAL_LABEL,
    LABEL_BINARY,
    LABEL_CONFIDENCE,
    QUALITY_FLAGS,
    N_FEATURES_MISSING,
]

# ============================================================================
# SECTION 2 — CONTROLLED VOCABULARIES
# ============================================================================

# ---- source_dataset --------------------------------------------------------
SOURCE_MOCK_LOCAL = "mock_local"   # generated by src/ingest/mock_generator.py
SOURCE_IOT23 = "iot23"             # derived from a local IoT-23 conn.log.labeled

# Operational sources — authorised, enterprise-owned telemetry ingested by the
# PRODUCT (src/api + src/ingest/operational_*.py), not by the research pipeline.
# Every such capture is UNLABELLED: it carries no ground truth, so every row is
# research_class=unmapped and can only ever yield a review-alert, never a
# trained or confirmed class. They are real wire captures (PROV_REAL_CAPTURE),
# but their label_confidence is CONF_UNLABELLED because no annotator inspected
# them. Operational data is never pooled with a training set. See
# docs/product-operation.md.
SOURCE_OP_ZEEK = "op_zeek"          # authorised local Zeek conn.log[.labeled]
SOURCE_OP_FLOW_CSV = "op_flow_csv"  # authorised CSV flow export (rich per-flow)
SOURCE_OP_NETFLOW = "op_netflow"    # authorised NetFlow-style CSV (no TCP flags)
SOURCE_OP_FIREWALL = "op_firewall"  # authorised firewall-flow CSV (coarsest)

OPERATIONAL_SOURCES: tuple[str, ...] = (
    SOURCE_OP_ZEEK,
    SOURCE_OP_FLOW_CSV,
    SOURCE_OP_NETFLOW,
    SOURCE_OP_FIREWALL,
)

# A COMPLETE Zeek log set — conn.log plus dns.log, http.log and ssl.log — rather
# than a connection log alone. This is the only source for which the resolution
# group is measurable at all.
#
# IoT-23 ships conn.log.labeled and nothing else, so a pipeline built on the
# dataset as distributed can never observe name resolution, an infrastructure
# fetch, or a TLS server name. Those are precisely the behaviours this project
# exists to evaluate. Replaying the original captures through Zeek locally
# regenerates the missing logs (see scripts/run_zeek.py), and this source marks
# an observation frame built from that fuller telemetry.
SOURCE_ZEEK_BUNDLE = "zeek_bundle"

SOURCE_DATASETS: tuple[str, ...] = (
    SOURCE_MOCK_LOCAL,
    SOURCE_IOT23,
    SOURCE_ZEEK_BUNDLE,
) + OPERATIONAL_SOURCES

# ---- capture_provenance ----------------------------------------------------
# Deliberately separate from source_dataset. source_dataset says WHICH corpus;
# capture_provenance says whether packets were ever observed on a real wire.
# Any table, figure or paper claim must be able to answer that question without
# consulting a second file.
PROV_SYNTHETIC = "synthetic_generated"   # numbers sampled locally; no packets
PROV_REAL_CAPTURE = "real_capture"       # aggregated from a real packet capture

CAPTURE_PROVENANCES: tuple[str, ...] = (PROV_SYNTHETIC, PROV_REAL_CAPTURE)

# ---- research_class : the 7-class taxonomy ---------------------------------
# Track A — real capture, IoT-23. Traditional (DNS/IP-based) botnet behaviour.
CLS_BENIGN_REAL = "benign_real"
CLS_TRADITIONAL_C2 = "traditional_c2"
CLS_TRADITIONAL_BOTNET = "traditional_botnet_activity"

# Track B — locally generated mock. The behaviour this project is ABOUT.
CLS_BENIGN_MOCK = "benign_mock"
CLS_BLOCKCHAIN_RESOLUTION_MOCK = "blockchain_resolution_mock"
CLS_VICTIM_RELAY_MOCK = "victim_relay_mock"
CLS_COMBINED_MOCK = "combined_mock"

TRACK_A_CLASSES: tuple[str, ...] = (
    CLS_BENIGN_REAL,
    CLS_TRADITIONAL_C2,
    CLS_TRADITIONAL_BOTNET,
)
TRACK_B_CLASSES: tuple[str, ...] = (
    CLS_BENIGN_MOCK,
    CLS_BLOCKCHAIN_RESOLUTION_MOCK,
    CLS_VICTIM_RELAY_MOCK,
    CLS_COMBINED_MOCK,
)
RESEARCH_CLASSES: tuple[str, ...] = TRACK_A_CLASSES + TRACK_B_CLASSES

# `unmapped` is NOT in RESEARCH_CLASSES and is NOT a trainable label.
# It is a DATA STATE: the source carried a label this project refuses to
# guess at. Such rows are retained for auditing, excluded from training, and
# counted in every report. At inference time the equivalent is ABSTENTION —
# the detector declines to emit a class — never a predicted category.
CLS_UNMAPPED = "unmapped"

TRACK_OF_CLASS: dict[str, str] = {
    **{c: "A" for c in TRACK_A_CLASSES},
    **{c: "B" for c in TRACK_B_CLASSES},
}

# Which classes are the positive (malicious) side of the binary view.
# NOTE for Track A: `traditional_c2` and `traditional_botnet_activity` are
# malicious, but they are malicious in the CONVENTIONAL way. They are not
# evidence about blockchain-resolution or victim-relay behaviour, and a Track-A
# score must never be presented as support for this project's thesis.
MALICIOUS_CLASSES: tuple[str, ...] = (
    CLS_TRADITIONAL_C2,
    CLS_TRADITIONAL_BOTNET,
    CLS_BLOCKCHAIN_RESOLUTION_MOCK,
    CLS_VICTIM_RELAY_MOCK,
    CLS_COMBINED_MOCK,
)
BENIGN_CLASSES: tuple[str, ...] = (CLS_BENIGN_REAL, CLS_BENIGN_MOCK)

# ---- label_confidence ------------------------------------------------------
# Never conflate "I generated this label myself" with "a dataset author
# annotated this". The first is exact by construction; the second inherits the
# annotator's error rate, and IoT-23's labels are themselves derived from
# capture-level knowledge rather than per-flow inspection.
CONF_SYNTHETIC_GROUND_TRUTH = "synthetic_ground_truth"
CONF_DATASET_ANNOTATED = "dataset_annotated"
# Operational telemetry the product ingests has NO label at all: no annotator,
# no dataset author, no ground truth. This value records that absence explicitly
# so an unlabelled operational row can never be mistaken for an annotated one,
# and so a model can never be trained on it while pretending it was.
CONF_UNLABELLED = "unlabelled_operational"

LABEL_CONFIDENCES: tuple[str, ...] = (
    CONF_SYNTHETIC_GROUND_TRUTH,
    CONF_DATASET_ANNOTATED,
    CONF_UNLABELLED,
)

# ---- quality_flags ---------------------------------------------------------
FLAG_MISSING_FEATURES = "missing_features"    # >=1 feature is NaN
FLAG_PROXY_FEATURES = "proxy_features"        # >=1 feature is an approximation
FLAG_LOW_FLOW_COUNT = "low_flow_count"        # window had too few flows
FLAG_SHORT_WINDOW = "short_window"            # window covers < min span
FLAG_UNMAPPED_LABEL = "unmapped_label"        # source label not in taxonomy
FLAG_SINGLE_PEER = "single_peer"              # only one remote peer seen
FLAG_LABEL_NOISE_INJECTED = "label_noise_injected"   # mock: label was flipped
# Real captures label individual FLOWS; this project's unit is a device-window,
# so a window can contain both benign and malicious flows. Aggregating to one
# class necessarily discards that. The flag carries the malicious flow fraction
# so a window that is 3% malicious is distinguishable from one that is 100%
# malicious — without it, a weak positive and an unambiguous one are the same
# row, and a reported false-negative rate cannot be interpreted.
FLAG_MIXED_LABEL_WINDOW = "mixed_label_window"

QUALITY_FLAG_NAMES: tuple[str, ...] = (
    FLAG_MISSING_FEATURES,
    FLAG_PROXY_FEATURES,
    FLAG_LOW_FLOW_COUNT,
    FLAG_SHORT_WINDOW,
    FLAG_UNMAPPED_LABEL,
    FLAG_SINGLE_PEER,
    FLAG_LABEL_NOISE_INJECTED,
    FLAG_MIXED_LABEL_WINDOW,
)

FLAG_SEP = ";"          # between flags
FLAG_ARG_SEP = ":"      # between a flag name and its argument
FLAG_LIST_SEP = "|"     # inside a flag argument, e.g. "missing_features:a|b"


def make_flags(flags: dict[str, list[str] | None] | None) -> str:
    """Render a flag dict to the canonical ``quality_flags`` string.

    ``{"missing_features": ["a", "b"], "low_flow_count": None}``
    becomes ``"missing_features:a|b;low_flow_count"``.

    Flags are emitted in QUALITY_FLAG_NAMES order so the string is stable and
    two runs producing the same flags produce byte-identical CSVs.
    """
    if not flags:
        return ""
    parts: list[str] = []
    for name in QUALITY_FLAG_NAMES:
        if name not in flags:
            continue
        arg = flags[name]
        if arg:
            parts.append(f"{name}{FLAG_ARG_SEP}{FLAG_LIST_SEP.join(sorted(arg))}")
        else:
            parts.append(name)
    return FLAG_SEP.join(parts)


def parse_flags(s: str | float | None) -> dict[str, list[str]]:
    """Inverse of :func:`make_flags`. Missing/NaN/empty all yield ``{}``."""
    if s is None or not isinstance(s, str) or not s.strip():
        return {}
    out: dict[str, list[str]] = {}
    for part in s.split(FLAG_SEP):
        part = part.strip()
        if not part:
            continue
        if FLAG_ARG_SEP in part:
            name, arg = part.split(FLAG_ARG_SEP, 1)
            out[name] = [a for a in arg.split(FLAG_LIST_SEP) if a]
        else:
            out[part] = []
    return out


# ============================================================================
# SECTION 3 — FEATURE COLUMNS
# ============================================================================
# Unchanged from the prototype, deliberately. The prototype's null result is a
# real finding; renaming or re-parameterising the features here would make the
# enterprise build's numbers incomparable to it for no scientific gain.
#
# UNIT OF ANALYSIS: one row = ONE DEVICE over ONE 5-MINUTE WINDOW.
# Not one flow. distinct_dst_ports, flow_fanout, scan_rate, login_burst_count
# and beacon_jitter are undefined for a single flow — they exist only as
# per-device aggregates over a window.

FEATURE_GROUPS: dict[str, list[str]] = {
    "resolution": [
        "ens_query_rate",        # queries/min to blockchain-name / RPC endpoints
        "rpc_endpoint_ratio",    # fraction of lookups to non-standard resolvers
        "resolution_entropy",    # randomness of resolved-name pattern (DGA-like)
        "serverlist_pull",       # server-list pull seen after resolution (0/1)
    ],
    "relay": [
        "bidir_flow_duration",   # seconds; relay flows are long-lived
        "flow_fanout",           # distinct peers the device exchanges with
        "upnp_addportmapping",   # UPnP AddPortMapping observed (0/1)
        "updownlink_ratio",      # up/down byte symmetry (relay tends to ~1.0)
    ],
    "infection": [
        "login_burst_count",     # Telnet/SSH login-burst attempts
        "scan_rate",             # outbound connection attempts/min
        "distinct_dst_ports",    # port variety touched
        "failed_conn_ratio",     # fraction of failed outbound connections
    ],
    "payload": [
        "beacon_interval",       # seconds; periodic C2 beaconing rhythm
        "beacon_jitter",         # variance around the beacon interval
        "rc4_string_score",      # LAB-ONLY — see LAB_ONLY_FEATURES
        "mean_pkt_size",         # average packet size
    ],
}

FEATURE_COLS: list[str] = [c for cols in FEATURE_GROUPS.values() for c in cols]

GROUP_OF_FEATURE: dict[str, str] = {
    c: g for g, cols in FEATURE_GROUPS.items() for c in cols
}

# The two groups whose independent value this project exists to measure.
NOVEL_GROUPS: tuple[str, ...] = ("resolution", "relay")
# The generic, already-solved signals that form the comparison base.
BASE_GROUPS: tuple[str, ...] = ("infection", "payload")

# Features not observable from encrypted network traffic in a real deployment.
# They need host telemetry or plaintext payload inspection, so they are
# lab-only. Every headline result is reported both WITH and WITHOUT them.
LAB_ONLY_FEATURES: tuple[str, ...] = ("rc4_string_score",)

# Binary (0/1) features — validated as such, and never scaled.
BINARY_FEATURES: tuple[str, ...] = ("serverlist_pull", "upnp_addportmapping")

# Inclusive value ranges enforced by the validator. None = unbounded above.
FEATURE_RANGES: dict[str, tuple[float, float | None]] = {
    "ens_query_rate": (0.0, None),
    "rpc_endpoint_ratio": (0.0, 1.0),
    "resolution_entropy": (0.0, 8.0),
    "serverlist_pull": (0.0, 1.0),
    "bidir_flow_duration": (0.0, None),
    "flow_fanout": (0.0, None),
    "upnp_addportmapping": (0.0, 1.0),
    "updownlink_ratio": (0.0, 5.0),
    "login_burst_count": (0.0, None),
    "scan_rate": (0.0, None),
    "distinct_dst_ports": (0.0, None),
    "failed_conn_ratio": (0.0, 1.0),
    "beacon_interval": (0.0, None),
    "beacon_jitter": (0.0, None),
    "rc4_string_score": (0.0, 1.0),
    "mean_pkt_size": (40.0, 1500.0),
}

ALL_COLS: list[str] = META_COLS + FEATURE_COLS


# ============================================================================
# SECTION 4 — PER-SOURCE FEATURE AVAILABILITY
# ============================================================================
# This is the machine-checkable form of the project's central limitation.
#
# IoT-23's lightweight distribution ships Zeek `conn.log.labeled` only — no
# dns.log, no http.log, no ssl.log, and no payload. So the features that
# DEFINE this project's novelty are the ones it cannot supply:
#
#   resolution : 3 of 4 unavailable  (only a weak proxy for rpc_endpoint_ratio)
#   relay      : 1 of 4 unavailable  (upnp_addportmapping needs SSDP/SOAP)
#
# That is why the thesis cannot be tested on IoT-23, and why Track A measures
# false alarms on real benign traffic rather than the thesis. Encoding it here
# means docs/limitations.md can be generated from code instead of asserted in
# prose, and a test can fail if anyone ever quietly claims otherwise.

AVAIL_COMPUTABLE = "computable"    # derivable exactly from the source's fields
AVAIL_PROXY = "proxy"              # approximated; flagged on every row
AVAIL_UNAVAILABLE = "unavailable"  # not derivable; emitted as NaN

# The five features NO flow log can supply, identical to IoT-23's gap: they need
# a dns.log / http.log (resolution), SSDP/SOAP payload (upnp_addportmapping), or
# plaintext inspection (rc4_string_score) that a connection record never carries.
# Every flow-derived source forces exactly these to NaN — and because
# src/features/derive.py computes exactly the OTHER eleven, this set is what
# keeps a flow-derived source in agreement with the deriver (see the agreement
# check in derive_features). Changing it here without changing the deriver, or
# vice versa, fails loudly rather than emitting fabricated zeros.
_FLOW_UNAVAILABLE: tuple[str, ...] = (
    "ens_query_rate",
    "resolution_entropy",
    "serverlist_pull",
    "upnp_addportmapping",
    "rc4_string_score",
)


def _flow_availability(proxy: tuple[str, ...]) -> dict[str, str]:
    """Availability map for a flow-derived source.

    The five canonical gaps are ``unavailable``, the named features are
    ``proxy`` (approximations flagged on every row), and everything else is
    ``computable``. The computable-plus-proxy union is therefore always the
    eleven features derive_features produces, so any source built this way
    satisfies the derive/availability agreement check by construction. Only the
    proxy set differs between sources — it is the honesty label for how much a
    given telemetry format actually measures versus approximates.
    """
    unknown = set(proxy) - set(FEATURE_COLS)
    if unknown:
        raise ValueError(f"unknown proxy feature(s): {sorted(unknown)}")
    overlap = set(proxy) & set(_FLOW_UNAVAILABLE)
    if overlap:
        raise ValueError(
            f"feature(s) cannot be both proxy and unavailable: {sorted(overlap)}")
    out: dict[str, str] = {}
    for c in FEATURE_COLS:
        if c in _FLOW_UNAVAILABLE:
            out[c] = AVAIL_UNAVAILABLE
        elif c in proxy:
            out[c] = AVAIL_PROXY
        else:
            out[c] = AVAIL_COMPUTABLE
    return out


FEATURE_AVAILABILITY: dict[str, dict[str, str]] = {
    SOURCE_MOCK_LOCAL: {c: AVAIL_COMPUTABLE for c in FEATURE_COLS},
    SOURCE_IOT23: {
        # resolution — needs dns.log / http.log, absent from conn.log.labeled
        "ens_query_rate": AVAIL_UNAVAILABLE,
        "rpc_endpoint_ratio": AVAIL_PROXY,   # non-53 resolver-port share only
        "resolution_entropy": AVAIL_UNAVAILABLE,
        "serverlist_pull": AVAIL_UNAVAILABLE,
        # relay
        "bidir_flow_duration": AVAIL_COMPUTABLE,
        "flow_fanout": AVAIL_COMPUTABLE,
        "upnp_addportmapping": AVAIL_UNAVAILABLE,   # needs SSDP/SOAP payload
        "updownlink_ratio": AVAIL_COMPUTABLE,
        # infection
        "login_burst_count": AVAIL_PROXY,    # attempts to 22/23/2323, not auth
        "scan_rate": AVAIL_COMPUTABLE,
        "distinct_dst_ports": AVAIL_COMPUTABLE,
        "failed_conn_ratio": AVAIL_COMPUTABLE,
        # payload
        "beacon_interval": AVAIL_COMPUTABLE,
        "beacon_jitter": AVAIL_COMPUTABLE,
        "rc4_string_score": AVAIL_UNAVAILABLE,      # needs plaintext payload
        "mean_pkt_size": AVAIL_COMPUTABLE,
    },
    # ---- operational sources (product ingest) ------------------------------
    # A Zeek conn.log from an authorised sensor carries exactly IoT-23's fields,
    # so its availability is identical: only rpc_endpoint_ratio and
    # login_burst_count are proxies. A rich CSV flow export is treated as
    # equally capable.
    SOURCE_OP_ZEEK: _flow_availability(
        ("rpc_endpoint_ratio", "login_burst_count")),
    SOURCE_OP_FLOW_CSV: _flow_availability(
        ("rpc_endpoint_ratio", "login_burst_count")),
    # NetFlow-style records are usually unidirectional and carry no TCP-flag
    # richness, so bidirectional pairing, connection outcome and byte symmetry
    # all become approximations on top of the two IoT-23 proxies.
    SOURCE_OP_NETFLOW: _flow_availability((
        "rpc_endpoint_ratio", "login_burst_count", "failed_conn_ratio",
        "updownlink_ratio", "bidir_flow_duration")),
    # A firewall flow log is coarser still: it rarely records packet counts, so
    # mean_pkt_size is a proxy as well.
    SOURCE_OP_FIREWALL: _flow_availability((
        "rpc_endpoint_ratio", "login_burst_count", "failed_conn_ratio",
        "updownlink_ratio", "bidir_flow_duration", "mean_pkt_size")),

    # ---- complete Zeek log set -------------------------------------------
    # The one source where the resolution group is measurable. Four of the five
    # features every flow log must leave NaN become computable here, because the
    # logs that carry them are present:
    #
    #   ens_query_rate       ssl.log server_name (TLS SNI) against the cited
    #                        RPC-gateway allowlist; http.log host as fallback
    #   rpc_endpoint_ratio   the same match as a share of the window's sessions
    #   resolution_entropy   dns.log query names
    #   serverlist_pull      http.log GET with a key-like parameter following a
    #                        gateway contact
    #   upnp_addportmapping  SSDP on UDP/1900 plus a SOAP control request
    #
    # rc4_string_score stays UNAVAILABLE. It needs plaintext payload, which no
    # Zeek log carries, and it is never approximated. Every headline result is
    # reported both with and without it.
    #
    # login_burst_count remains a PROXY for the same reason it is one on IoT-23:
    # connection attempts to 22/23/2323 are visible, authentication outcomes are
    # not. rpc_endpoint_ratio is promoted from proxy to computable because it is
    # no longer inferred from port numbers but read from the server name.
    SOURCE_ZEEK_BUNDLE: {
        # resolution — the group this project exists to evaluate
        "ens_query_rate": AVAIL_COMPUTABLE,
        "rpc_endpoint_ratio": AVAIL_COMPUTABLE,
        "resolution_entropy": AVAIL_COMPUTABLE,
        "serverlist_pull": AVAIL_COMPUTABLE,
        # relay
        "bidir_flow_duration": AVAIL_COMPUTABLE,
        "flow_fanout": AVAIL_COMPUTABLE,
        "upnp_addportmapping": AVAIL_COMPUTABLE,
        "updownlink_ratio": AVAIL_COMPUTABLE,
        # infection
        "login_burst_count": AVAIL_PROXY,
        "scan_rate": AVAIL_COMPUTABLE,
        "distinct_dst_ports": AVAIL_COMPUTABLE,
        "failed_conn_ratio": AVAIL_COMPUTABLE,
        # payload
        "beacon_interval": AVAIL_COMPUTABLE,
        "beacon_jitter": AVAIL_COMPUTABLE,
        "rc4_string_score": AVAIL_UNAVAILABLE,   # needs plaintext; never faked
        "mean_pkt_size": AVAIL_COMPUTABLE,
    },
}


def features_by_availability(source: str, status: str) -> list[str]:
    """Feature columns with the given availability status for ``source``."""
    table = FEATURE_AVAILABILITY[source]
    return [c for c in FEATURE_COLS if table[c] == status]


def unavailable_features(source: str) -> list[str]:
    """Features that must be emitted as NaN for ``source``."""
    return features_by_availability(source, AVAIL_UNAVAILABLE)


def proxy_features(source: str) -> list[str]:
    """Features that are approximations for ``source`` (flag every row)."""
    return features_by_availability(source, AVAIL_PROXY)


def availability_summary(source: str) -> dict[str, dict[str, int]]:
    """Per-group counts of computable / proxy / unavailable for ``source``.

    Used by src/reports to generate the limitation table in the paper, so the
    numbers in the write-up are read from the schema rather than retyped.
    """
    table = FEATURE_AVAILABILITY[source]
    out: dict[str, dict[str, int]] = {}
    for group, cols in FEATURE_GROUPS.items():
        counts = {AVAIL_COMPUTABLE: 0, AVAIL_PROXY: 0, AVAIL_UNAVAILABLE: 0}
        for c in cols:
            counts[table[c]] += 1
        out[group] = counts
    return out


# ============================================================================
# SECTION 5 — FEATURE-SET SELECTION HELPERS
# ============================================================================

def features_for_groups(group_names) -> list[str]:
    """Feature columns belonging to the named groups, in canonical order."""
    wanted = set(group_names)
    unknown = wanted - set(FEATURE_GROUPS)
    if unknown:
        raise KeyError(f"unknown feature group(s): {sorted(unknown)}")
    return [c for g, cols in FEATURE_GROUPS.items() if g in wanted for c in cols]


def features_excluding(group_name: str) -> list[str]:
    """Feature columns with one group removed (drop-one diagnostic)."""
    if group_name not in FEATURE_GROUPS:
        raise KeyError(f"unknown feature group: {group_name}")
    return [c for g, cols in FEATURE_GROUPS.items()
            if g != group_name for c in cols]


def network_observable_features(cols=None) -> list[str]:
    """Drop the lab-only features from ``cols`` (default: all features)."""
    cols = list(FEATURE_COLS if cols is None else cols)
    return [c for c in cols if c not in LAB_ONLY_FEATURES]


def is_malicious_class(research_class: str) -> bool:
    return research_class in MALICIOUS_CLASSES


def binary_label_for(research_class: str) -> int:
    """Map a research_class to the 0/1 binary view.

    Raises on `unmapped` — an unmapped row has no defensible binary label and
    must be excluded from training rather than silently called benign.
    """
    if research_class in BENIGN_CLASSES:
        return 0
    if research_class in MALICIOUS_CLASSES:
        return 1
    raise ValueError(
        f"no binary label for research_class={research_class!r}; "
        f"`{CLS_UNMAPPED}` rows must be excluded, not defaulted"
    )
